export const TODOS_ASYNC_INIT = 'TODOS_ASYNC_INIT';

export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const LOAD_TODOS_FALIURE = 'LOAD_TODOS_FALIURE';

export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FALIURE = 'ADD_TODO_FALIURE';

export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FALIURE = 'UPDATE_TODO_FALIURE';

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FALIURE = 'DELETE_TODO_FALIURE';

export const UPDATE_CURRENT_TODO = 'UPDATE_CURRENT_TODO';